# Generated by Django 4.2.6 on 2023-11-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
