# Generated by Django 4.2.6 on 2023-11-01 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_auto_20231101_1726"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="updated_at",
            new_name="last_update",
        ),
        migrations.RemoveField(
            model_name="address",
            name="zip",
        ),
    ]
