# Generated by Django 4.2.6 on 2023-11-01 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_rename_updated_at_product_last_update_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="birthdate",
            new_name="birth_date",
        ),
    ]
