# Generated by Django 4.2.6 on 2023-11-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_rename_birthdate_customer_birth_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
